# Generated by Django 2.0.3 on 2018-03-23 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180323_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 9, 32, 15, 801686)),
        ),
    ]
