# Generated by Django 2.0.3 on 2018-03-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20180323_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='readed_num',
            new_name='read_num',
        ),
    ]
